name: Build Android APK (arm64-v8a)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: "3.38.5"
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Ensure Android platform exists (repo may not include android/)
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -d "android" ]; then
            echo "android/ folder not found -> generating Android platform with flutter create"
            flutter create . --platforms=android
          fi

      - name: Flutter pub get
        run: flutter pub get

      - name: Build APK (debug, split per ABI)
        id: build_apk
        shell: bash
        continue-on-error: true
        run: |
          set -euo pipefail
          mkdir -p artifact
          set +e
          flutter build apk --debug --split-per-abi 2>&1 | tee artifact/flutter_build.log
          code=${PIPESTATUS[0]}
          set -e
          echo "exit_code=$code" >> "$GITHUB_OUTPUT"
          exit 0

      - name: Collect arm64-v8a APK + create ERROR_SUMMARY.txt
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          out_dir="build/app/outputs/flutter-apk"
          if [ -d "$out_dir" ]; then
            # Copy only arm64-v8a to avoid confusion.
            cp "$out_dir"/*arm64-v8a*.apk artifact/ 2>/dev/null || true
            # Also keep universal debug if it exists (optional).
            cp "$out_dir"/app-debug.apk artifact/ 2>/dev/null || true
          fi

          {
            echo "Build exit code: ${{ steps.build_apk.outputs.exit_code }}"
            echo
            echo "Files in artifact/:"
            ls -lah artifact || true
            echo
            echo "=== Last 200 lines of flutter_build.log ==="
            tail -n 200 artifact/flutter_build.log || true
          } > artifact/ERROR_SUMMARY.txt

      - name: Upload artifact (APK + logs)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: artifact
          if-no-files-found: warn
          compression-level: 6

      - name: Fail job if build failed
        if: ${{ steps.build_apk.outputs.exit_code != '0' }}
        run: exit 1        
